apiVersion: v1
kind: Service
metadata:
  name: The name of the service #ex: backend

spec:
  type: ClusterIP
  ports:
  - targetPorts: if not given this will match port #ex: 80
    port: this is mandatry #ex: 80

  selector:
    app: must match the pod template #ex: myapp
    type: must match the pod template #ex: backend-end

service commands:
kubectl create -f service.yml: creates a service
kubectl apply -f service.yml: creates and updates a service
kubestl get services: shows a list of the services
kubectl describe serive: gets detailed info about the service
